title: Emotional Support Objects
author: Stephen Feldman
email: sfeldman@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  This is the most badass blog in the history of man kind.

# social links
twitter_username: StephenFeldman3 # DO NOT include the @ character, or else the build will fail!
github_username:  StephenF26 # DO NOT include the @ character, or else the build will fail!
facebook_username: Stephen Feldman
instagram_username: d_stephf26
snapchar_username: d-stephf26

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
